### ISSUE TITLE
Change in tests "Altom" name in imports for C# package

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/EXAMPLES-NewInputSystem--CoinCollector-CSharp#5]
## Description
 
- Apply in tests the changes brought in the `feature-proxy` branch by https://github.com/alttester/AltTester-Unity-SDK/issues/984 for **the next release of the tester** (for pro 1.0 release)
- Update README.md
## Additional info
- epic: https://github.com/alttester/AltTester-Unity-SDK/issues/1038
- the PR for this issue should be merged on the `main` branch only when we have the released tester for pro 1.0

**Comment by MihaiCuc98** [comment]
Test results:
![image](https://github.com/alttester/EXAMPLES-NewInputSystem--CoinCollector-CSharp/assets/113912901/0b55444a-ec89-4e2c-b41c-2e9743ad41dd)

I will move this ticket into `Done`.
